# Pavucontrol floating
windowrule = match:class (.*org.pulseaudio.pavucontrol.*), float on, size 700 600, center on, pin on

# Waypaper
windowrule = match:class (.*waypaper.*), float on, size 900 700, center on, pin on
# Blueman Manager
windowrule = match:class (blueman-manager), float on, size 800 600, center on

# nwg-look
windowrule = match:class (nwg-look), float on, size 700 600, move (monitor_w*0.10) (monitor_h*0.20), pin on

# nwg-displays
windowrule = match:class (nwg-displays), float on, size 900 600, move (monitor_w*0.10) (monitor_h*0.20), pin on

# System Mission Center
windowrule = match:class (io.missioncenter.MissionCenter), float on, size 900 600, center on, pin on

# System Mission Center Preference Window
windowrule = match:class (missioncenter), match:title ^(Preferences)$, float on, center on, pin on

# Gnome Calculator
windowrule = match:class (org.gnome.Calculator), float on, size 700 600, center on

# Emoji Picker Smile
windowrule = match:class (it.mijorus.smile), float on, pin on, move (monitor_w-window_w-40) 90

# Hyprland Share Picker
windowrule = match:class (hyprland-share-picker), float on, pin on, size 600 400, center on

# General floating
windowrule = match:class (dotfiles-floating), float on, size 1000 700, center on

# Floating for Ghostty
windowrule = match:class (ml4w.dotfiles.floating), float on, size 1000 700, center on, pin on

# SwayNC
layerrule = match:namespace swaync-control-center, blur on, ignore_alpha 0.5
layerrule = match:namespace swaync-notification-window, blur on, ignore_alpha 0.5

# XDG Desktop Portal
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# QT
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1

# GDK
env = GDK_SCALE,1

# Toolkit Backend
env = GDK_BACKEND,wayland,x11,*
env = CLUTTER_BACKEND,wayland

# Mozilla
env = MOZ_ENABLE_WAYLAND,1

# Set the cursor size for xcursor
env = XCURSOR_SIZE,24

# Ozone
env = OZONE_PLATFORM,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,wayland



