# -----------------------------------------------------
# Environment Variables
# name: "Default"
# -----------------------------------------------------

# Default Settings in ml4w.conf

env = WLR_DRM_DEVICES,/dev/dri/card0:/dev/dri/card1
