color0       #3A393A
color8       #979088
color1       #806D5C
color9       #806D5C
color2       #C56B3F
color10      #C56B3F
color3       #8C8C67
color11      #8C8C67
color4       #F5921B
color12      #F5921B
color5       #E69B89
color13      #E69B89
color6       #C2AE97
color14      #C2AE97
color7       #D8CEC3
color15      #D8CEC3